services:
  cims-web:
    image: ghcr.io/projectcims/cims-web:latest
    ports:
      - "80:8080"

  cims-api:
    image: ghcr.io/projectcims/cims-api:latest
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    secrets:
      - db-password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: CIMS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  db-password:
    external: true
