services:
  cims-web:
    image: sc3l3t0n/cims-web:latest
    ports:
      - "80:8080"

  cims-api:
    image: sc3l3t0n/cims-api:latest
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CIMS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
